update nav color
bckrm/www-gatsby pull request #44
Opened 2021-02-28 16:25 UTC by kcbreuil

2021-02-28 16:25 UTC, kcbreuil commented
closes #41

2021-02-28 18:03 UTC, asasmith requested changes

2021-02-28 18:03 UTC, asasmith commented on web/src/components/NewNav.js
> +    color: ${props => props.darkTheme ? 'var(--brand-9)' : '#2E444F' }
This logic is not working. `#2e444f` is the color being applied on every page. We can start removing the `darkTheme` logic (for now, just remove it from this component).

2021-03-01 02:44 UTC, asasmith commented on web/src/components/NewNav.js
> +    ${tw`fixed py-8 top-0 w-full z-10`}
I don't think this should change. Is this branch up to date with `production`?

2021-03-01 02:53 UTC, asasmith approved these changes

2021-03-01 02:53 UTC, merged